### ISSUE TITLE
项目运行有AssertError

### ISSUE THREAD

**Issue by hymanliu2015** [hyzhan43/PlayAndroid#1]
java.lang.AssertionError: annotation tree hasn't been attributed yet: @kotlin.Metadata(mv = {1, 1, 10}, bv = {1, 0, 2}, k = 1, d1 = {"\u00002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u000b\n\u0002\b\u0007\n\u0002\u0010\u0002\n\u0000\n\u0002\u0010\b\n\u0002\b\u0006\n\u0002\u0018\u0002\n\u0002\b\u0002\u0018\u0000 \u00182\b\u0012\u0004\u0012\u00020\u00020\u00012\u00020\u0003:\u0001\u0018B\u0005\u00a2\u0006\u0002\u0010\u0004J\b\u0010\r\u001a\u00020\u000eH\u0016J\b\u0010\u000f\u001a\u00020\u0010H\u0016J\b\u0010\u0011\u001a\u00020\u000eH\u0016J\r\u0010\u0012\u001a\u00020\u0013H\u0016\u00a2\u0006\u0002\u0010\u0014J\u0012\u0010\u0015\u001a\u00020\u000e2\b\u0010\u0016\u001a\u0004\u0018\u00010\u0017H\u0016R+\u0010\u0007\u001a\u00020\u00062\u0006\u0010\u0005\u001a\u00020\u00068B@BX\u0082\u008e\u0002\u00a2\u0006\u0012\n\u0004\b\u000b\u0010\f\u001a\u0004\b\u0007\u0010\b\"\u0004\b\t\u0010\n\u00a8\u0006\u0019"}, d2 = {"Lzqx/rj/com/playandroid/account/view/LoginActivity;", "Lzqx/rj/com/mvvm/base/LifecycleActivity;", "Lzqx/rj/com/playandroid/account/vm/AccountViewModel;", "Landroid/view/View$OnClickListener;", "()V", "", "", "isLogin", "()Z", "setLogin", "(Z)V", "isLogin$delegate", "Lzqx/rj/com/mvvm/common/Preference;", "dataObserver", "", "getLayoutId", "", "initView", "onBackPressed", "error/NonExistentClass", "()Lerror/NonExistentClass;", "onClick", "v", "Landroid/view/View;", "Companion", "app_debug"}) |  
-- | --

**Comment by hyzhan43** [comment]
可能是支持库的版本不一样，compileSdkVersion 28。试试
或者
看看这个解决方案：https://stackoverflow.com/questions/52413078/cannot-access-activitycompatapi23-kotlin-androidx-dagger-2-17
