### ISSUE TITLE
想问一下项目结构，总感觉adapter包放data里面有点奇怪，如下面工程截图

### ISSUE THREAD

**Issue by davidgerka** [hyzhan43/PlayAndroid#3]
这个问题困扰许久，实在忍不住要问了[手动狗头]，这个adapter包有无其他的位置可以放呢，总感觉别扭

![wx20190307-113805](https://user-images.githubusercontent.com/13624423/53930996-5c731f80-40ce-11e9-8c54-54ceb1e1ab99.png)

**Comment by hyzhan43** [comment]
这个嘛。你不说我还不觉得。哈哈哈，可能当时没考虑好，我下个版本改成data 同级目录下。感觉会好点。你觉得呢？
有问题就提嘛，大家一起交流学习~

**Comment by davidgerka** [comment]
跟data同级或者是放到view里面跟fragment同级  应该好点 哈哈
