### ISSUE TITLE
代码混淆报错

### ISSUE THREAD

**Issue by taozhixiang** [hyzhan43/PlayAndroid#4]
我非常喜欢这套架构，然后用这个mvvm作为自己项目的依赖库。但是后期混淆代码一直报错。您可以写一个混淆的配置文件吗？

**Comment by hyzhan43** [comment]
非常抱歉，时隔那么久才回复你，最近一位大佬（@TinyHai ）提了混淆的 Pull requests 。合并到项目中，你可以参考一下。
